const Technologies = [
  "10μm",
  "25μm",
  "50μm",
  "single-cell SRT",
  "Stereo-Seq",
  "10x Visium",
  "Spatial Transcriptomics",
  "MERFISH",
  "STARmap",
  "Slide-seqV2",
  "scRNA",
  "snRNA",
  "scATAC",
  "RNAseq",
  "GeoMx DSP",
  "CUT&Tag",
  "Slide-seq",
  "seqFISH+",
  "VINE-seq",
  "ClampFISH",
  "Geo-seq",
  "Seq-Scope",
  "CITE-seq",
  "EASI-FISH",
  "PIC-seq",
  "Tomo-seq",
  "sci-Space",
  "ClumpSeq",
  "XYZeq",
  "sci-ATAC-seq",
  "DBiT-seq",
  "LCM-seq",
  "sciMAP-ATAC-seq",
  "APEX-seq",
  "Proximity RNA-seq",
  "HDST",
  "seqFish",
]

export default Technologies