const Topics = [
  'Normal atlas', 
  'Development', 
  "Cancer",
  'Injury',
  "Plants",
  "Heart failure",
  'Melanoma', 
  'Repair',
  'Carcinoma', 
  "Breast cancer",
  "Pancreatic cancer",
  "Pan cancer",
  'Embryonic brain',
  "Brain cortex",
  "Olfactory bulb",
  "Atopic dermatitis",
  'Regeneration',
  ]
export default Topics
